openapi: 3.0.3
info:
  title: greenfield-project
  version: 0.0.1
tags:
  - name: auth
  - name: route
servers:
  - url: http://localhost:3000/
    description: 開発環境
security:
  - cookieAuth: []
paths:
  /signup:
    post:
      tags:
        - "auth"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                name:
                  type: string
                password:
                  type: string
              required:
                - email
                - name
                - password
      responses:
        200:
          description: 成功
        401:
          description: 認証エラー
        403:
          description: 認可エラー
        404:
          description: リソース未検出エラー
        500:
          description: サーバーエラー
  /signin:
    post:
      tags:
        - "auth"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password
      responses:
        200:
          description: 成功
        401:
          description: 認証エラー
        403:
          description: 認可エラー
        404:
          description: リソース未検出エラー
        500:
          description: サーバーエラー
  /route:
    get:
      tags:
        - "route"
      description: 出発地、目的のエリア、所用時間からおすすめのルートを提示
      parameters:
        - name: originLatitude
          in: query
          schema:
            type: number
        - name: originLongitude
          in: query
          schema:
            type: number
        - name: area
          in: query
          schema:
            type: string
        - name: requiredTime
          in: query
          schema:
            type: number
      responses:
        200:
          description: 成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RouteItem"
        401:
          description: 認証エラー
        403:
          description: 認可エラー
        404:
          description: リソース未検出エラー
        500:
          description: サーバーエラー
components:
  schemas:
    RouteItem:
      type: object
      properties:
        totalDuration:
          type: number
          description: 総所要時間 (秒)
          example: 120
        waypoints:
          type: array
          items:
            type: object
            properties:
              location:
                type: object
                properties:
                  latitude:
                    type: number
                  longitude:
                    type: number
              spotName:
                type: string
              spotDescription:
                type: string
              spotAddress:
                type: string
