openapi: 3.0.3
info:
  title: greenfield-project
  version: 0.0.1
tags:
  - name: auth
servers:
  - url: http://localhost:3000/
    description: 開発環境
security:
  - cookieAuth: []
paths:
  /signup:
    post:
      tags:
        - "auth"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                name:
                  type: string
                password:
                  type: string
              required:
                - email
                - name
                - password
      responses:
        200:
          description: 成功
        401:
          description: 認証エラー
        403:
          description: 認可エラー
        404:
          description: リソース未検出エラー
        500:
          description: サーバーエラー
  /signin:
    post:
      tags:
        - "auth"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password
      responses:
        200:
          description: 成功
        401:
          description: 認証エラー
        403:
          description: 認可エラー
        404:
          description: リソース未検出エラー
        500:
          description: サーバーエラー
 